#include "Serializer.hpp"
#include <iostream>

int main(void)
{
	Data ColonelReyel;

	ColonelReyel.songName = "Aurélie";
	ColonelReyel.text = "Aurélie n'a que 16 ans et elle attend un enfant,\n"
						"Ses amies et ses parents lui conseillent l'avortement.\n"
						"Elle n'est pas d'accord, elle voit les choses autrement.\n"
						"Elle dit qu'elle se sent prête pour qu'on l'appelle \"maman\".\n"
						"Celui-ci c'est\n"
						"Pour toutes les Aurélie\n"
						"Celles qui ont donné la vie\n"
						"Pour toutes les Aurélie\n"
						"Oy, mère à tout prix\n"
						"\n"
						"Elle est en seconde dans un lycée de banlieue,.\n"
						"Sort avec un mec de son quartier depuis peu\n"
						"Il est comme elle aime c'est-a-dire un peu plus vieux,\n"
						"Il a l'air amoureux, ils ont tout pour être heureux.\n"
						"Elle l'a jamais fait, elle attendait juste le bon gars\n"
						"Là ell.e se dit bingo, ils sont seuls dans la Twingo.\n"
						"Donc ça va swinguer, elle enlève son tanga\n"
						"Il réussit le ace comme Tsonga\n"
						"Oui, mais voilà 9 mois plus tard\n"
						"Il n'assume pas et se sauve comme un bâtard.\n"
						"Elle a découvert qu'en fait il est fêtard,\n"
						"Résultat elle se retrouve seule dans cette histoire\n"
						"\n"
						"Aurélie n'a que 16 ans et elle attend un enfant,\n"
						"Ses amies et ses parents lui conseillent l'avortement.\n"
						"Elle n'est pas d'accord, elle voit les choses autrement.\n"
						"Elle dit qu'elle se sent prête pour qu'on l'appelle \"maman\".\n"
						"Celui-ci c'est\n"
						"Pour toutes les Aurélie\n"
						"Celles qui ont donné la vie\n"
						"Pour toutes les Aurélie\n"
						"Oy, mère à tout prix\n"
						"\n"
						"\n"
						"Je peux te dire que toute sa vie elle se rappellera\n"
						"Elle se rappellera le jour elle l'annonça\n"
						"Où elle l'annonça à sa mère et son papa\n"
						"Elle annonça qu'elle était enceinte de 3 mois\n"
						"Elle ne s'attendait à ce qu'ils sautent de joie\n"
						"Mais elle espérait quand même qu'ils fassent preuve de bonne foi\n"
						"Le moins que l'on puisse dire c'est que ce ne fut pas le cas\n"
						"Et la galère commença\n"
						"\n"
						"Aurélie n'a que 16 ans et elle attend un enfant,\n"
						"Ses amies et ses parents lui conseillent l'avortement.\n"
						"Elle n'est pas d'accord, elle voit les choses autrement.\n"
						"Elle dit qu'elle se sent prête pour qu'on l'appelle \"maman\".\n"
						"Celui-ci c'est\n"
						"Pour toutes les Aurélie\n"
						"Celles qui ont donné la vie\n"
						"Pour toutes les Aurélie\n"
						"Oy, mère à tout prix\n"
						"\n"
						"\n"
						"Elle a du construire très rapidement un foyer\n"
						"Faire face à ses responsabilités pour le loyer\n"
						"Trouver un travail coûte que coûte pour le payer\n"
						"Elle aura tout essayé\n"
						"Comme on dit dans les quartiers, elle s'est saignée\n"
						"Pour trouver quelqu'un qui veuille bien la renseigner\n"
						"Je crois qu'on n'est pas VIP comme Mathilde Seigner\n"
						"De ne pas lâcher l'affaire ça lui a enseigné\n"
						"Oh, on a tous connu une fille dans le cas d'Aurélie\n"
						"Une pour qui grossesse est synonyme de délit\n"
						"Rejetée par ses amis mais surtout par sa famille\n"
						"Qui n'accepte pas qu'elle souhaite donner la vie\n"
						"Voilà ce que je dirais si je devais donner mon avis\n"
						"Mettre un enfant au monde ne devrait-pas être puni\n"
						"C'est la plus belle chose qui soit et si tu le nies\n"
						"C'est que tu n'as rien compris !\n"
						"\n"
						"Aurélie n'a que 16 ans et elle attend un enfant,\n"
						"Ses amies et ses parents lui conseillent l'avortement.\n"
						"Elle n'est pas d'accord, elle voit les choses autrement.\n"
						"Elle dit qu'elle se sent prête pour qu'on l'appelle \"maman\".\n"
						"Celui-ci c'est\n"
						"Pour toutes les Aurélie\n"
						"Celles qui ont donné la vie\n"
						"Pour toutes les Aurélie\n"
						"Oy, mère à tout prix";

	uintptr_t  ptr = Serializer::serialize(&ColonelReyel);
	Data * data_recover = Serializer::deserialize(ptr);

	std::cout << data_recover->songName << std::endl;
	std::cout << data_recover->text << std::endl;

	return 0;
}